version: '3.4'

services:
  webordersapi:
    container_name: application
    image: ${DOCKER_REGISTRY-}webordersapi
    ports:
        - 5006:443
        - 8008:80
    build:
      context: .
      dockerfile: WebOrdersApi/Dockerfile
    networks:
      - internal

  database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432 
    networks:
      - internal

networks:
  internal:
    driver: bridge

